package com.company.sensorsAPI.controllers;

import com.company.sensorsAPI.SensorSimulation;
import com.company.sensorsAPI.entities.Room;
import com.company.sensorsAPI.repositories.RoomRepository;
import com.company.sensorsAPI.entities.Sensor;
import com.company.sensorsAPI.repositories.SensorRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path = "/room")
public class RoomController {
    @Autowired // This means to get the bean called sensorRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RoomRepository roomRepository;
    @Autowired
    private SensorRepository sensorRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    void addNewRoom(@RequestBody Room room) {
        Room room1 = new Room(room.getName());
        roomRepository.save(room1);
        Sensor sensor = new Sensor(10, 0, 0, room.getName() + "_sensor", false, 21.5, room1);
        sensorRepository.save(sensor);
    }

    @PostMapping(path = "/delete") // Map ONLY POST Requests
    public @ResponseBody
    boolean removeRoom(@RequestBody Room room) {
        if(SensorSimulation.deleteFlag) {
            Iterable<Room> rooms = roomRepository.findAll();
            Iterable<Sensor> sensors = sensorRepository.findAll();
            for (Room room1 : rooms) {
                if (room.getName().equals(room1.getName())) {
                    for (Sensor sensor : sensors) {
                        if (sensor.getSensorName().equals(room1.getName() + "_sensor")) {

                            sensorRepository.delete(sensor);
                        }
                    }
                    roomRepository.delete(room1); //TODO: můžeme mazat místnost a zároveň její senzor a je to správně? (cascade...)
                    return true;
                }
            }
        }else{
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("removing");
            removeRoom(room);
        }
        return false;
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Room> getAllRooms() {
        // This returns a JSON or XML with the users
        Iterable<Room> rooms = roomRepository.findAll();
        return rooms;
    }
}