package com.company.sensorsAPI;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path = "/sensor")
public class RoomController {
    @Autowired // This means to get the bean called sensorRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RoomRepository roomRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    Room addNewSensor(@RequestBody Room room) {
        //TODO: kde ukládat senzory
        SensorFactory.createSensor(room);
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return roomRepository.save(room);
    }

    @GetMapping(path = "/add")
    public @ResponseBody
    Iterable<Room> getAllSensors() {
        // This returns a JSON or XML with the users
        return roomRepository.findAll();
    }
}