package com.company.sensorsAPI;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path = "/sensor")
public class SensorController {
    @Autowired // This means to get the bean called sensorRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SensorRepository sensorRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    Sensor addNewSensor(@RequestBody Sensor sensor) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return sensorRepository.save(sensor);
    }

    @GetMapping(path = "/add")
    public @ResponseBody
    Iterable<Sensor> getAllSensors() {
        // This returns a JSON or XML with the users
        return sensorRepository.findAll();
    }
}