package com.company.sensorsAPI;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path = "/statistics_data")
public class StatisticsDataController {

    @Autowired // This means to get the bean called sensorRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StatisticsDataRepository statisticsDataRepository;


}
